### ISSUE TITLE
new validator

### ISSUE THREAD

**Issue by webpatser** [bitsongofficial/networks#218]
Hi,

I would like to add my bitsong validator. since the migration from 1 -> 2 has taken place, all the docs are out of date I think?

Should I still generate a gentx json file and make a PR here. If so: In what directory should I place it? bitsong-1, bitsong-2, bitsong2b?

If there is another way, what is the correct method to enrol as a new validator?

Kind regards.

**Comment by angelorc** [comment]
Hi and welcome to bitsong.

Yes the guide must be updated in our website. If you need any help join in our discord channel https://discord.gg/ptzXyJVN
